# This is a basic workflow to help you get started with Actions

name: CI

# Controls when the action will run. 
on:
  # Triggers the workflow on push or pull request events but only for the main branch
  push:
    branches: [ main, dev ]
  pull_request:
    branches: [ main, dev ]

jobs:
  
  build:
    name: Build android apk
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v2
      - uses: actions/setup-java@v1
        with:
          java-version: '12x'
      - uses: subosito/flutter-action@v1.5.0
        with:
          flutter-version: '2.0.5'
      - run: flutter pub get
      - run: flutter clean
      - run: flutter build apk --split-per-abi
